### ISSUE TITLE
Glove not work

### ISSUE THREAD

**Issue by NikolaJyun** [advancedfx/nSkinz#27] opened 2022-03-28 00:12 UTC
**advancedfx specific?**

Please check that the bug is specific to the advancedfx modded version and not present in the original https://github.com/namazso/nSkinz and otherwise report it there in stead please.

**Describe the bug**
Glove not work ![Counter-Strike Global Offensive_2022 03 28-08 07](https://user-images.githubusercontent.com/22559124/160307354-d4276f84-33b0-46f9-9c5b-1adbeb59b2b3.png)

**Comment by dtugend** [comment] 2022-03-28 17:50
Please provide more information and your settings used and maybe demo.

Also make sure you are really using the latest version: https://github.com/advancedfx/nSkinz/releases/tag/advancedfx-v0.1.16

**Comment by NikolaJyun** [comment] 2022-03-29 01:17
@dtugend I found a problem. When the player who wants to modify has gloves, modifying other gloves will fail.
Because I try to modify another player without gloves he will work fine.

**Comment by dtugend** [comment] 2022-03-29 07:51
This problem used to be in older versions of advancedfx-nSkins, I can not reproduce it in demos with the latest advancedfx-nSkinz.

As said please make sure you are using the latest version https://github.com/advancedfx/nSkinz/releases/tag/advancedfx-v0.1.16
If you are sure, please right click it in Windows -> Properties -> FileSize. There's two numbers of sizes, I need the smaller one to compare.

**Comment by dtugend** [comment] 2022-03-29 09:30
> @dtugend I found a problem. When the player who wants to modify has gloves, modifying other gloves will fail. Because I try to modify another player without gloves he will work fine.

Did I understand you correctly, that you meant:
- the player in the demo you want to modify already has a glove?

Or did you mean the CS:GO game owner regardless of which player is modified in the demo?

Edit: regardless see above reply please.

**Comment by NikolaJyun** [comment] 2022-03-29 23:20
Yes! If I modify a player already wearing gloves in the demo,It will not function properly, like the picture attached at the beginning.


But modify the player without gloves and he will function normally.

![image](https://user-images.githubusercontent.com/22559124/160721774-47eb5c04-cb13-4b4c-94a2-089af2d3b5be.png)

**Comment by dtugend** [comment] 2022-03-30 04:05
This seems to be the correct nSkinz.dll version.

Please provide the following information e.g. by email to contact@advancedfx.org:
1. Link to this issue (https://github.com/advancedfx/nSkinz/issues/27).
2. Full command used to load nSkinz.dll from HLAE (`mirv_loadlibrary ....`).
3. Your nSkinz.json file in your Counter-Strike directiory (e.g. in C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive), this should contain the config you use in the demo.
4. A link to the demo in question, so I can download and test it with the same settings.

**Comment by dtugend** [comment] 2022-03-30 18:53
if it doesn't contain sensitive info, yo ucan also provide the info here

**Comment by dtugend** [comment] 2022-04-04 15:27
Didn't get an email or reply, did it get lost or is it sort of solved already?

**Comment by dtugend** [comment] 2022-04-30 19:28
closing this issue until further info is provided

**Closed as completed by dtugend** 2022-04-30 19:28 UTC
Labels: question
