### ISSUE TITLE
Can't Change Glove

### ISSUE THREAD

**Issue by dontkillmyDab** [advancedfx/nSkinz#20] opened 2021-12-18 15:51 UTC
i cant change my glove,when i chose the Sporty,my glove always be Amphibious,even i chose the else skin,and if i chose the Motorcycle or Specialist,my glove will cant load,and if i chose the Hydra or Handwarp,my glove will be so fkn dark,idk why,maybe the key is cache,but idk the path of cache
![bug2](https://user-images.githubusercontent.com/89676593/146647065-92e31180-a19d-408e-8177-91b5f37ef0c1.png)

![bug1](https://user-images.githubusercontent.com/89676593/146647063-025a2c7b-410c-49a8-879b-a4d3e53da765.png)

![bug](https://user-images.githubusercontent.com/89676593/146647060-3204c64d-5b08-478c-999a-92e95e111a60.png)

**Comment by dtugend** [comment] 2021-12-18 17:24
I tried to reproduce the issue, but it works fine on my end, apart from the handwarp, which is because you are using work_shop_default which does not exist for handwrap.

Please make super sure you are using really the latest version:
https://github.com/advancedfx/nSkinz/releases/latest (currently nSkinz-advancedfx-v0.1.13)
**We didn't issue an update notifcation**, since those still point at the old repository and they currently can not be told apart from screenshot.

Also **don't forget to hit update and rewind the demo to a round start**!

**Comment by dontkillmyDab** [comment] 2021-12-18 18:16
rly thx, tomorrow I'll try it again

**Comment by dtugend** [comment] 2021-12-29 15:16
Hi. Closing until we hear back from you.
Don't forget to not inject nSkinz.dll in custom loader, but use e.g. `mirv_loadlibrary "C:\path\to\nSkinz.dll"` in console instead.

**Closed as completed by dtugend** 2021-12-29 15:16 UTC
Labels: question
